use std::collections::BTreeSet;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

use walkdir::WalkDir;

use crate::finding::{AnalysisReport, Claim, ClaimKind, Evidence, Finding, Location};
use crate::performance;
use crate::rust_facts::scan_rust_repository;

const SKIPPED_RUST_DIRS: &[&str] = &[".git", "target", "node_modules", ".venv", "vendor"];

#[derive(Debug, Clone, Eq, PartialEq)]
pub struct ExplicitTest {
    pub name: String,
    pub path: PathBuf,
    pub line: usize,
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FilteredLibTestCommand {
    pub workflow_path: PathBuf,
    pub line: usize,
    pub command: String,
    pub filter: String,
}

#[derive(Debug, Default)]
pub struct CiTestFilterReport {
    pub tests: Vec<ExplicitTest>,
    pub possible_module_fragments: BTreeSet<String>,
    pub commands: Vec<FilteredLibTestCommand>,
    pub parse_failures: Vec<(PathBuf, String)>,
}

pub fn analyze_ci_test_filters(root: &Path) -> Result<CiTestFilterReport, Box<dyn Error>> {
    let mut report = CiTestFilterReport::default();
    collect_workflow_commands(root, &mut report)?;

    // A repository with no supported selector has no CI-test finding to build,
    // so avoid paying for a Rust inventory at all.
    if report.commands.is_empty() {
        return Ok(report);
    }

    collect_explicit_tests(root, &mut report)?;

    report
        .tests
        .sort_by(|a, b| a.path.cmp(&b.path).then(a.line.cmp(&b.line)));
    report.commands.sort_by(|a, b| {
        a.workflow_path
            .cmp(&b.workflow_path)
            .then(a.line.cmp(&b.line))
    });
    report.parse_failures.sort_by(|a, b| a.0.cmp(&b.0));

    Ok(report)
}

pub fn build_ci_test_filter_analysis(root: &Path, report: &CiTestFilterReport) -> AnalysisReport {
    let mut analysis = AnalysisReport::new(
        "ci-test-filter-inventory",
        root.to_string_lossy().into_owned(),
    );

    if report.commands.is_empty() {
        analysis.claims.push(Claim::new(
            ClaimKind::Proven,
            "No supported literal `cargo test --lib FILTER` workflow commands were found.",
        ));
        return analysis;
    }

    analysis.claims.push(Claim::new(
        ClaimKind::Proven,
        format!(
            "The syntax scan found {} explicit `#[test]` function declaration(s) and {} supported filtered `cargo test --lib` workflow command(s).",
            report.tests.len(),
            report.commands.len()
        ),
    ));

    if !report.parse_failures.is_empty() {
        let mut claim = Claim::new(
            ClaimKind::Unknown,
            format!(
                "{} Rust file(s) failed to parse, so the explicit test inventory is incomplete.",
                report.parse_failures.len()
            ),
        );
        for (path, error) in report.parse_failures.iter().take(5) {
            claim = claim.with_evidence(Evidence::at(
                error.clone(),
                Location::new(relative_path(root, path), None),
            ));
        }
        analysis.claims.push(claim);
        return analysis;
    }

    if report.tests.is_empty() {
        analysis.claims.push(Claim::new(
            ClaimKind::Unknown,
            "No explicit `#[test]` declarations were found, so this experiment has no useful declared-test inventory to compare.",
        ));
        return analysis;
    }

    for command in &report.commands {
        if has_possible_explicit_match(report, &command.filter) {
            continue;
        }

        let workflow_location = Location::new(
            relative_path(root, &command.workflow_path),
            Some(command.line),
        );

        let proven = Claim::new(
            ClaimKind::Proven,
            format!(
                "The workflow contains the supported literal command `{}` with test filter `{}`.",
                command.command, command.filter
            ),
        )
        .with_evidence(Evidence::at(
            "Recognized `cargo test --lib FILTER` command.",
            workflow_location.clone(),
        ));

        let mut observed = Claim::new(
            ClaimKind::Observed,
            format!(
                "None of the {} explicit `#[test]` function names or declared Rust module names found by this syntax scan contains `{}`.",
                report.tests.len(),
                command.filter
            ),
        );
        for test in report.tests.iter().take(5) {
            observed = observed.with_evidence(Evidence::at(
                format!("Explicit test `{}`.", test.name),
                Location::new(relative_path(root, &test.path), Some(test.line)),
            ));
        }

        let unknown = Claim::new(
            ClaimKind::Unknown,
            "This syntax-only inventory does not enumerate tests generated by macros or other build-time mechanisms. The command should be executed with test listing when zero-selection must be proven.",
        );

        analysis.findings.push(
            Finding::new(
                "ci-test-filter-inventory-miss",
                "CI test filter has no explicit test-name match",
            )
            .at(workflow_location)
            .with_claim(proven)
            .with_claim(observed)
            .with_claim(unknown)
            .with_question(format!(
                "Is this workflow step still selecting the intended library test for `{}`?",
                command.filter
            )),
        );
    }

    analysis
}

fn has_possible_explicit_match(report: &CiTestFilterReport, filter: &str) -> bool {
    report.tests.iter().any(|test| test.name.contains(filter))
        || report
            .possible_module_fragments
            .iter()
            .any(|fragment| fragment.contains(filter))
}

fn collect_explicit_tests(
    root: &Path,
    report: &mut CiTestFilterReport,
) -> Result<(), Box<dyn Error>> {
    let scan = scan_rust_repository(root, &BTreeSet::new(), SKIPPED_RUST_DIRS)?;
    performance::record_rust_scan(scan.parsed_files, scan.cache_hits);
    performance::record_rust_prefiltered(scan.prefiltered_files);

    for file in scan.files {
        if let Some(error) = file.facts.parse_error {
            report.parse_failures.push((file.path, error));
            continue;
        }

        for test in file.facts.explicit_tests {
            report.tests.push(ExplicitTest {
                name: test.name,
                path: file.path.clone(),
                line: test.line,
            });
        }
        report
            .possible_module_fragments
            .extend(file.facts.module_names);
    }

    Ok(())
}

fn collect_workflow_commands(
    root: &Path,
    report: &mut CiTestFilterReport,
) -> Result<(), Box<dyn Error>> {
    let workflows = root.join(".github/workflows");
    if !workflows.is_dir() {
        return Ok(());
    }

    for entry in WalkDir::new(&workflows).max_depth(1) {
        let entry = entry?;
        if !entry.file_type().is_file() || !is_yaml(entry.path()) {
            continue;
        }

        let source = fs::read_to_string(entry.path())?;
        for (index, line) in source.lines().enumerate() {
            let Some(command) = workflow_shell_line(line) else {
                continue;
            };
            let Some(filter) = parse_filtered_lib_test_command(command) else {
                continue;
            };
            report.commands.push(FilteredLibTestCommand {
                workflow_path: entry.path().to_path_buf(),
                line: index + 1,
                command: command.to_string(),
                filter,
            });
        }
    }

    Ok(())
}

fn workflow_shell_line(line: &str) -> Option<&str> {
    let trimmed = line.trim();
    if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.ends_with('\\') {
        return None;
    }

    let step = trimmed.strip_prefix("- ").map(str::trim).unwrap_or(trimmed);
    let candidate = step.strip_prefix("run:").map(str::trim).unwrap_or(step);
    if candidate.starts_with("cargo test ") || candidate.starts_with("cargo +") {
        Some(candidate)
    } else {
        None
    }
}

fn parse_filtered_lib_test_command(command: &str) -> Option<String> {
    let tokens: Vec<_> = command.split_whitespace().collect();
    if tokens.len() < 4 || tokens[0] != "cargo" {
        return None;
    }

    let mut index = 1;
    if tokens
        .get(index)
        .is_some_and(|token| token.starts_with('+'))
    {
        if !is_simple_toolchain_selector(tokens[index]) {
            return None;
        }
        index += 1;
    }
    if tokens.get(index).copied() != Some("test") {
        return None;
    }
    index += 1;

    let mut saw_lib = false;
    let mut filter = None;

    while index < tokens.len() {
        let token = tokens[index];
        if token == "--" {
            break;
        }

        match token {
            "--lib" => saw_lib = true,
            "--locked"
            | "--quiet"
            | "-q"
            | "--release"
            | "--no-fail-fast"
            | "--no-default-features"
            | "--all-features"
            | "--frozen"
            | "--offline" => {}
            "--features" | "--color" | "--jobs" | "-j" | "--profile" | "--target"
            | "--target-dir" | "--config" => {
                index += 1;
                if index >= tokens.len() {
                    return None;
                }
            }
            "-p" | "--package" | "--workspace" | "--test" | "--tests" | "--bin" | "--bins"
            | "--example" | "--examples" | "--doc" | "--all-targets" | "--exclude"
            | "--manifest-path" => return None,
            _ if token.starts_with('-') => return None,
            _ => {
                if filter.is_some() {
                    return None;
                }
                let candidate = token.trim_matches(['\'', '"']);
                if !is_simple_test_filter(candidate) {
                    return None;
                }
                filter = Some(candidate.to_string());
            }
        }

        index += 1;
    }

    saw_lib.then_some(filter?).filter(|value| !value.is_empty())
}

fn is_simple_toolchain_selector(value: &str) -> bool {
    let Some(selector) = value.strip_prefix('+') else {
        return false;
    };
    !selector.is_empty()
        && selector
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '.' | '-' | '_'))
}

fn is_simple_test_filter(value: &str) -> bool {
    !value.is_empty()
        && value
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
}

fn is_yaml(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|ext| ext.to_str()),
        Some("yml" | "yaml")
    )
}

fn relative_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

#[cfg(test)]
mod tests {
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::*;

    fn unique_temp_dir(name: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!(
            "cargo-cultist-{name}-{}-{nanos}",
            std::process::id()
        ))
    }

    #[test]
    fn recognizes_narrow_filtered_lib_commands() {
        assert_eq!(
            parse_filtered_lib_test_command("cargo test --locked --lib test_rollback"),
            Some("test_rollback".to_string())
        );
        assert_eq!(
            parse_filtered_lib_test_command(
                "cargo test --features io_uring --lib test_rollback -- --nocapture"
            ),
            Some("test_rollback".to_string())
        );
        assert_eq!(
            parse_filtered_lib_test_command(
                "cargo +1.88.0 test --lib test_rollback --locked --no-default-features"
            ),
            Some("test_rollback".to_string())
        );
    }

    #[test]
    fn accepts_simple_cargo_toolchain_selectors() {
        assert!(is_simple_toolchain_selector("+1.88.0"));
        assert!(is_simple_toolchain_selector("+stable"));
        assert!(is_simple_toolchain_selector("+nightly-2026-08-19"));
        assert!(!is_simple_toolchain_selector("+"));
        assert!(!is_simple_toolchain_selector("+stable;echo"));
    }

    #[test]
    fn skips_commands_with_ambiguous_target_selection() {
        assert_eq!(
            parse_filtered_lib_test_command("cargo test -p block --lib test_rollback"),
            None
        );
        assert_eq!(
            parse_filtered_lib_test_command("cargo test --test integration test_rollback"),
            None
        );
    }

    #[test]
    fn skips_complex_shell_and_filter_forms() {
        assert_eq!(
            parse_filtered_lib_test_command("cargo test --lib foo::test_rollback"),
            None
        );
        assert_eq!(
            parse_filtered_lib_test_command("cargo test --lib test_rollback && echo ok"),
            None
        );
        assert_eq!(
            parse_filtered_lib_test_command("cargo +stable;echo test --lib test_rollback"),
            None
        );
    }

    #[test]
    fn extracts_inline_and_block_workflow_commands() {
        assert_eq!(
            workflow_shell_line("      run: cargo test --lib test_rollback"),
            Some("cargo test --lib test_rollback")
        );
        assert_eq!(
            workflow_shell_line("          cargo +1.88.0 test --lib test_rollback"),
            Some("cargo +1.88.0 test --lib test_rollback")
        );
        assert_eq!(
            workflow_shell_line("      - run: cargo test --lib test_rollback"),
            Some("cargo test --lib test_rollback")
        );
        assert_eq!(
            workflow_shell_line("          cargo test --lib test_rollback"),
            Some("cargo test --lib test_rollback")
        );
        assert_eq!(workflow_shell_line("        run: |"), None);
    }

    #[test]
    fn declared_module_names_suppress_qualified_filter_misses() {
        let mut report = CiTestFilterReport::default();
        report.tests.push(ExplicitTest {
            name: "works".to_string(),
            path: PathBuf::from("src/foo.rs"),
            line: 1,
        });
        report.possible_module_fragments.insert("foo".to_string());

        assert!(has_possible_explicit_match(&report, "foo"));
        assert!(has_possible_explicit_match(&report, "works"));
        assert!(!has_possible_explicit_match(&report, "src"));
        assert!(!has_possible_explicit_match(&report, "missing"));
    }

    #[test]
    fn no_supported_workflow_skips_rust_inventory() {
        let root = unique_temp_dir("ci-tests-no-command");
        fs::create_dir_all(root.join("src")).unwrap();
        fs::write(root.join("src/lib.rs"), [0xff, 0xfe, 0xfd]).unwrap();

        let report = analyze_ci_test_filters(&root).unwrap();

        assert!(report.commands.is_empty());
        assert!(report.tests.is_empty());
        assert!(report.parse_failures.is_empty());
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn supported_workflow_records_prefiltered_rust_work() {
        let root = unique_temp_dir("ci-tests-prefilter");
        fs::create_dir_all(root.join(".github/workflows")).unwrap();
        fs::create_dir_all(root.join("src")).unwrap();
        fs::write(
            root.join(".github/workflows/ci.yml"),
            "steps:\n  - run: cargo test --lib existing_test\n",
        )
        .unwrap();
        fs::write(root.join("src/lib.rs"), "#[test]\nfn existing_test() {}\n").unwrap();
        fs::write(root.join("src/value.rs"), "pub const VALUE: usize = 42;\n").unwrap();

        let (report, counters) = performance::capture(|| analyze_ci_test_filters(&root).unwrap());

        assert_eq!(report.commands.len(), 1);
        assert_eq!(report.tests.len(), 1);
        assert!(report.parse_failures.is_empty());
        assert_eq!(counters.rust_files_parsed, 1);
        assert_eq!(counters.rust_files_prefiltered, 1);

        fs::remove_dir_all(root).unwrap();
    }
}
